version: "3.8" #docker composerのバージョンの指定
services:
  nodejs:
    build: ./container/nodejs/ #buildするdockerfileの位置
    container_name: nodejs #作成するdockerコンテナの名前
    volumes:
      - ./nodejs:/nodejs #docker内と共有するフォルダの指定
    working_dir: /nodejs #docker内に入った時の初期パスの指定
    ports:
      - 3000:3000 #コンテナにバインドするポートの指定（左:自分のPCポート、右:dookerコンテナのポート）
    tty: true #コンテナが勝手に終了しないための設定
    stdin_open: true #標準入出力とエラー出力をコンテナに結びつける設定
    environment:
      - CHOKIDAR_USEPOLLING=true #ホットリロードを行う設定
